getwd()
data <- read.table("./data/power/household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE, dec=".")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
subset <- subset(data, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
str(subset)

subset$Global_active_power <- as.numeric(subset$Global_active_power)
subset$datetime <- paste(subset$Date, subset$Time)
subset$datetime <- as.POSIXct(subset$datetime)
str(subset)
plot(subset$Global_active_power~subset$datetime, type="l", ylab="Global Active Power (kilowatts)")
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()
