getwd()
data <- read.table("./data/power/household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE, dec=".")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
subset <- subset(data, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
str(subset)

subset$datetime <- paste(subset$Date, subset$Time)
subset$datetime <- as.POSIXct(subset$datetime)
subset$Voltage <- as.numeric(subset$Voltage)
subset$Global_reactive_power <- as.numeric(subset$Global_reactive_power)
subset$Global_active_power <- as.numeric(subset$Global_active_power)
subset$Sub_metering_1 <- as.numeric(subset$Sub_metering_1)
subset$Sub_metering_2 <- as.numeric(subset$Sub_metering_2)
subset$Sub_metering_3 <- as.numeric(subset$Sub_metering_3)
str(subset)

par(mfrow=c(2,2), mar=c(4,4,1,1), oma=c(0,2,0,2))
plot(subset$Global_active_power~subset$datetime, type="l", ylab="Global Active Power")
plot(subset$Voltage~subset$datetime, type="l", ylab="Voltage")
plot(subset$Sub_metering_1~subset$datetime, type="l", ylab="Energy sub metering")
lines(subset$Sub_metering_2~subset$datetime, col="red")
lines(subset$Sub_metering_3~subset$datetime, col="blue")
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(subset$Global_reactive_power~subset$datetime, type="l", ylab="Global Rective Power")
dev.copy(png, file="plot4.png", height=480, width=480)
dev.off()
